### ISSUE TITLE
Out of memory errors while running example codes

### ISSUE THREAD

**Issue by qiyuanpang** [bmxam/SlepcWrap.jl#5] opened 2023-09-07 20:50 UTC
I installed PetscWrap and SlepcWrap on my ubuntu machine. I used PETSc 3.16.1 and SLEPc 3.16.3. 
Here is the running environment:

`julia> Pkg.status()
Status `/scratch/zt1/project/hzyang-prj/user/haoranli/julia/environments/v1.8/Project.toml`
  [7d9fca2a] Arpack v0.5.4
  [6e4b80f9] BenchmarkTools v1.3.2
  [336ed68f] CSV v0.10.11
  [aaaa29a8] Clustering v0.15.4
  [a93c6f00] DataFrames v1.6.1
  [864edb3b] DataStructures v0.18.15
  [31c24e10] Distributions v0.25.100
  [42fd0dbc] IterativeSolvers v0.9.2
  [898213cb] LowRankApprox v0.5.5
  [23992714] MAT v0.10.5
  [33e6dc65] MKL v0.6.1
  [0c723cd3] MKLSparse v1.1.0
⌅ [5be22e1c] PetscWrap v0.1.5
  [af69fa37] Preconditioners v0.6.1
  [c3679e3b] SlepcWrap v0.1.3
  [bc48ee85] Tullio v0.3.5
  [37e2e46d] LinearAlgebra
  [de0858da] Printf
  [9a3f8284] Random
  [2f01184e] SparseArrays
  [8dfed614] Test`

When I ran the example code using 

`mpirun -n 1 --mca opal_warn_on_missing_libcuda 0 julia helmholtz.jl`

I got the following errors:

`[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Out of memory. This could be due to allocating
[0]PETSC ERROR: too large an object or bleeding by not properly
[0]PETSC ERROR: destroying unneeded objects.
[0]PETSC ERROR: Memory allocated 0 Memory used by process 1000681472
[0]PETSC ERROR: Try running with -malloc_dump or -malloc_view for info.
[0]PETSC ERROR: Memory requested 48
[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.16.1, Nov 01, 2021
[0]PETSC ERROR: julia on a  named compute-b5-1.zaratan.umd.edu by haoranli Thu Sep  7 16:41:02 2023`

**Comment by bmxam** [comment] 2024-05-13 15:02
closed as duplicate of #6

**Closed as completed by bmxam** 2024-05-13 15:02 UTC
